//! `rbb bid-pbn`: bid every deal of a PBN file and write it back with our
//! auctions, in the layout bba-cli writes (so tools that read bba-cli's
//! output read ours): a `% PBN` / `% Generated by` / `% CC1` / `% CC2`
//! header, and per board `[Auction]` rows with `=n=` note references,
//! `[Note "n:text"]` tags after them, `[Declarer]` and `[Contract]`.
//!
//! The input is edited in place (`PbnDocument`): every tag we do not own —
//! `[Deal]`, `[DoubleDummyTricks]`, `[OptimumResultTable]`, commentary,
//! `%` directives — is kept byte for byte.

use std::path::Path;

use bridge_encodings::pbn::{prevailing_newline, split_lines, PbnDocument};
use bridge_types::{Auction, Call, Direction, Hand, ScoringMethod};
use rayon::prelude::*;
use rbb_engine::{DealAuction, Engine};

pub struct Options {
    /// Force these calls at the start of every auction.
    pub prefix: Vec<Call>,
    /// Override each board's `[Scoring]` (default: the board's, else MP).
    pub scoring: Option<ScoringMethod>,
    /// A note for every call a rule explains, not only alerts.
    pub all_meanings: bool,
    /// Set `[Event]` on every board.
    pub event: Option<String>,
    /// Stop an auction after this many calls.
    pub max_calls: usize,
    /// For the `% CC1` / `% CC2` header lines.
    pub ns_card: String,
    pub ew_card: String,
}

#[derive(Debug, Default)]
pub struct Stats {
    pub deals: usize,
    pub auctions: usize,
    pub errors: usize,
    /// Auctions stopped at `max_calls` (finished with `AP`).
    pub runaway: usize,
}

/// The name the players' tags get.
const PLAYER: &str = "rbb";

/// Tags derived from the auction. A board we cannot bid loses them all, so a
/// previous run's auction never stands under a board that failed this time.
const AUCTION_TAGS: [&str; 5] = ["Declarer", "Contract", "Result", "Score", "Auction"];

/// Bid every board of `input` (PBN text) and return the annotated file.
pub fn bid_pbn(input: &str, engine: &Engine, opts: &Options) -> Result<(String, Stats), String> {
    let newline = prevailing_newline(input);
    let mut doc = PbnDocument::parse(&strip_owned_header(input)).map_err(|e| e.to_string())?;
    let boards = doc.boards().to_vec();

    let results: Vec<Result<(Direction, DealAuction), String>> = boards
        .par_iter()
        .map(|board| {
            let mut hands: [Hand; 4] = Default::default();
            for dir in [Direction::North, Direction::East, Direction::South, Direction::West] {
                let h = board.deal.hand(dir);
                if h.len() != 13 {
                    return Err(format!(
                        "{} has {} cards; every hand needs 13",
                        dir.to_char(),
                        h.len()
                    ));
                }
                hands[dir.to_index()] = h.clone();
            }
            let dealer = board.dealer.unwrap_or(Direction::North);
            let scoring = opts
                .scoring
                .or_else(|| board.extra_tag("Scoring").and_then(ScoringMethod::from_pbn))
                .unwrap_or_default();
            engine
                .bid_deal(&hands, dealer, board.vulnerable, scoring, &opts.prefix, opts.max_calls)
                .map(|a| (dealer, a))
        })
        .collect();

    let mut stats = Stats {
        deals: boards.len(),
        ..Stats::default()
    };
    for (idx, (board, result)) in boards.iter().zip(&results).enumerate() {
        let label = board
            .board_id
            .clone()
            .or(board.number.map(|n| n.to_string()))
            .unwrap_or_else(|| (idx + 1).to_string());
        let e = |e: bridge_encodings::ParseError| format!("board {label}: {e}");
        if let Some(event) = &opts.event {
            doc.set_tag(idx, "Event", event).map_err(e)?;
        }
        if doc.tag(idx, "Board").is_none() {
            doc.set_tag(idx, "Board", &label).map_err(e)?;
        }
        if board.dealer.is_none() {
            // Bid as North; say so.
            doc.set_tag(idx, "Dealer", "N").map_err(e)?;
        }
        if doc.tag(idx, "Vulnerable").is_none() {
            doc.set_tag(idx, "Vulnerable", board.vulnerable.to_pbn())
                .map_err(e)?;
        }
        for seat in ["North", "East", "South", "West"] {
            doc.set_tag(idx, seat, PLAYER).map_err(e)?;
        }
        if let Some(s) = opts.scoring {
            doc.set_tag(idx, "Scoring", scoring_tag(s)).map_err(e)?;
        }
        // Our notes replace any the file had.
        while doc.tag(idx, "Note").is_some() {
            doc.remove_tag(idx, "Note").map_err(e)?;
        }
        match result {
            Ok((dealer, auction)) => {
                stats.auctions += 1;
                let mut calls: Vec<Call> = auction.calls.iter().map(|c| c.step.call.clone()).collect();
                if !auction.complete {
                    stats.runaway += 1;
                    eprintln!(
                        "board {label}: the auction did not end in {} calls; finished with AP",
                        opts.max_calls
                    );
                }
                let (rows, notes) = annotated_auction(auction, opts.all_meanings);
                let mut a = Auction::new(*dealer);
                calls.extend(std::iter::repeat_n(Call::Pass, 3));
                for c in calls {
                    if a.is_complete() {
                        break;
                    }
                    a.add_call(c);
                }
                let (contract, declarer) = match a.final_contract() {
                    Some(fc) => (fc.to_pbn(), fc.declarer.to_char().to_string()),
                    None => ("Pass".to_string(), String::new()),
                };
                doc.set_tag(idx, "Declarer", &declarer).map_err(e)?;
                doc.set_tag(idx, "Contract", &contract).map_err(e)?;
                // They described the old contract.
                doc.remove_tag(idx, "Result").map_err(e)?;
                doc.remove_tag(idx, "Score").map_err(e)?;
                // The notes follow the auction rows, as PBN 2.1 3.5.5 and
                // bba-cli place them: written as the section's last rows.
                let mut lines = rows;
                lines.extend(notes.iter().map(|n| format!("[Note \"{n}\"]")));
                let lines: Vec<&str> = lines.iter().map(String::as_str).collect();
                doc.set_section(idx, "Auction", &dealer.to_char().to_string(), &lines)
                    .map_err(e)?;
            }
            Err(msg) => {
                stats.errors += 1;
                eprintln!("board {label}: {msg}");
                for tag in AUCTION_TAGS {
                    doc.remove_tag(idx, tag).map_err(e)?;
                }
            }
        }
    }
    let header = [
        "% PBN 2.1".to_string(),
        format!("% Generated by rbb {}", env!("CARGO_PKG_VERSION")),
        format!("% CC1 - {}", opts.ns_card),
        format!("% CC2 - {}", opts.ew_card),
    ];
    let mut out: String = header.iter().map(|l| format!("{l}{newline}")).collect();
    out.push_str(&doc.to_pbn());
    Ok((out, stats))
}

fn scoring_tag(s: ScoringMethod) -> &'static str {
    match s {
        ScoringMethod::IMP => "IMP",
        _ => "MP",
    }
}

/// A call as bba-cli writes it: `1N`, not `1NT`.
fn call_text(c: &Call) -> String {
    c.to_pbn().replace("NT", "N")
}

/// The auction's rows (four calls each, column-aligned, `=n=` after a call
/// with a note) and the notes, `n:text`. A note explains every alerted or
/// announced call; with `all_meanings`, every call a rule explains, followed
/// by what the call showed (` | 15-17 HCP, balanced`).
fn annotated_auction(auction: &DealAuction, all_meanings: bool) -> (Vec<String>, Vec<String>) {
    let mut notes = Vec::new();
    let mut entries = Vec::new();
    for c in &auction.calls {
        let s = &c.step;
        let text = s.rule.as_ref().and_then(|_| {
            let explanation = s.explanation.clone().unwrap_or_default();
            if all_meanings {
                let shown = s.knowledge.summary();
                Some(if shown.is_empty() || shown == explanation {
                    explanation
                } else {
                    format!("{explanation} | {shown}")
                })
            } else if s.alert.is_some() {
                Some(explanation)
            } else {
                None
            }
        });
        let call = call_text(&s.call);
        match text.map(|t| note_text(&t)).filter(|t| !t.is_empty()) {
            Some(t) => {
                notes.push(format!("{}:{t}", notes.len() + 1));
                entries.push(format!("{call} ={}=", notes.len()));
            }
            None => entries.push(call),
        }
    }
    if !auction.complete {
        entries.push("AP".into());
    }
    let rows = entries
        .chunks(4)
        .map(|chunk| {
            let mut line = String::new();
            for (j, entry) in chunk.iter().enumerate() {
                if j + 1 == chunk.len() {
                    line.push_str(entry);
                } else {
                    let width = if entry.len() <= 4 { 6 } else { entry.len() + 4 };
                    line.push_str(&format!("{entry:<width$}"));
                }
            }
            line.trim_end().to_string()
        })
        .collect();
    (rows, notes)
}

/// Safe inside a one-line quoted tag value.
fn note_text(s: &str) -> String {
    s.replace('"', "'").replace(['\r', '\n'], " ").trim().to_string()
}

/// `text` without a previous run's header (bba-cli's or ours), so headers do
/// not stack. Only the `%` lines at the very top are looked at.
fn strip_owned_header(text: &str) -> String {
    let mut out = String::with_capacity(text.len());
    let mut in_header = true;
    for (content, term) in split_lines(text) {
        in_header = in_header && content.starts_with('%');
        let owned = {
            let l = content.trim_end();
            l.starts_with("% PBN ")
                || l.starts_with("% Generated by ")
                || l.starts_with("% CC1 - ")
                || l.starts_with("% CC2 - ")
        };
        if in_header && owned {
            continue;
        }
        out.push_str(content);
        out.push_str(term);
    }
    out
}

/// Read, bid, write. `output` `-` is stdout.
pub fn run_files(input: &Path, output: &Path, engine: &Engine, opts: &Options) -> Result<Stats, String> {
    let text =
        std::fs::read_to_string(input).map_err(|e| format!("{}: {e}", input.display()))?;
    let (out, stats) = bid_pbn(&text, engine, opts)?;
    if output == Path::new("-") {
        print!("{out}");
    } else {
        std::fs::write(output, out).map_err(|e| format!("{}: {e}", output.display()))?;
    }
    Ok(stats)
}

#[cfg(test)]
mod tests {
    use super::*;

    fn engine() -> Engine {
        let modules =
            rbb_engine::compile_modules(rbb_assets::RULE_FILES.iter().copied()).unwrap();
        let card = bridge_card::bbsa::import(rbb_assets::card("21GF-DEFAULT").unwrap(), None)
            .unwrap()
            .0;
        Engine::new(&card, &card, &modules)
    }

    fn opts() -> Options {
        Options {
            prefix: Vec::new(),
            scoring: None,
            all_meanings: false,
            event: None,
            max_calls: 60,
            ns_card: "a.bbsa".into(),
            ew_card: "b.bbsa".into(),
        }
    }

    const INPUT: &str = "% PBN 2.1\n% Generated by bba-cli\n% CC1 - old.bbsa\n% CC2 - old.bbsa\n%HRTitleEvent \"t\"\n[Event \"t\"]\n[Board \"1\"]\n[Dealer \"N\"]\n[Vulnerable \"None\"]\n[Deal \"N:AK52.KJ7.Q94.K83 QJ3.Q95.KJ3.QJ74 T64.AT832.A2.T62 987.64.T8765.A95\"]\n[Contract \"7N\"]\n[Result \"3\"]\n[Auction \"N\"]\n7N    Pass  Pass  Pass\n[Note \"1:old\"]\n[OptimumResultTable \"Declarer;Denomination\\2R;Result\\2R\"]\nN NT  9\n\n";

    #[test]
    fn writes_auction_notes_and_contract_and_keeps_the_rest() {
        let (out, stats) = bid_pbn(INPUT, &engine(), &opts()).unwrap();
        assert_eq!((stats.deals, stats.auctions, stats.errors), (1, 1, 0));
        assert!(out.starts_with("% PBN 2.1\n% Generated by rbb "), "{out}");
        assert_eq!(out.matches("% CC1").count(), 1, "{out}");
        assert!(out.contains("% CC1 - a.bbsa\n"), "{out}");
        assert!(out.contains("%HRTitleEvent \"t\""), "{out}");
        assert!(out.contains("[Auction \"N\"]\n1N "), "{out}");
        assert!(!out.contains("1:old"), "{out}");
        assert!(!out.contains("[Result"), "{out}");
        assert!(out.contains("N NT  9"), "{out}");
        assert!(out.contains("[North \"rbb\"]"), "{out}");
        assert!(!out.contains("[Contract \"7N\"]"), "{out}");
        // 1NT is announced and the transfer alerted: both get notes, placed
        // after the auction rows.
        assert!(out.contains("1N =1=    Pass  2D =2="), "{out}");
        assert!(out.contains("[Note \"2:Transfer to hearts\"]\n[OptimumResultTable"), "{out}");
        // Reads back.
        let boards = bridge_encodings::pbn::read_pbn(&out).unwrap();
        let a = boards[0].auction.as_ref().unwrap();
        assert!(a.is_complete());
        assert_eq!(a.get_note(1).is_some(), true);
    }

    #[test]
    fn all_meanings_notes_every_explained_call() {
        let mut o = opts();
        o.all_meanings = true;
        let (out, _) = bid_pbn(INPUT, &engine(), &o).unwrap();
        assert!(out.contains("1N =1="), "{out}");
        assert!(out.contains("HCP"), "{out}");
    }

    #[test]
    fn a_board_that_cannot_be_bid_loses_its_auction() {
        let bad = INPUT.replace("987.64.T8765.A95", "987.64.T8765.A9");
        let (out, stats) = bid_pbn(&bad, &engine(), &opts()).unwrap();
        assert_eq!(stats.errors, 1);
        assert!(!out.contains("[Auction"), "{out}");
    }
}
