#!/usr/bin/env python3
"""Write a grid spec of random hands for one decision, for bulk probing.

    probes/gen_hands.py OUT.toml --count 2000 --hcp 9 9 --max-major 3 \
        --min-len 2 --max-len 5 --prefix "1NT Pass" --scoring MP IMP

Hands for the deciding seat are random within the constraints; each hand
gets its own random balanced 15-17 partner from the other 39 cards. Then `rbb grid OUT.toml` and analyse
.rbb-cache/grids/<name>/grid.json.
"""
import argparse
import random

RANKS = "AKQJT98765432"
HCP = {"A": 4, "K": 3, "Q": 2, "J": 1}


def deal13(rng, avoid=()):
    deck = [(s, r) for s in range(4) for r in RANKS if (s, r) not in avoid]
    return rng.sample(deck, 13)


def pbn(cards):
    return ".".join(
        "".join(sorted((r for s2, r in cards if s2 == s), key=RANKS.index)) for s in range(4)
    )


def hcp(cards):
    return sum(HCP.get(r, 0) for _, r in cards)


def lengths(cards):
    return [sum(1 for s2, _ in cards if s2 == s) for s in range(4)]


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument("out")
    ap.add_argument("--count", type=int, default=1000)
    ap.add_argument("--hcp", type=int, nargs=2, default=[9, 9])
    ap.add_argument("--max-major", type=int, default=3, help="most cards in either major")
    ap.add_argument("--min-len", type=int, default=2)
    ap.add_argument("--max-len", type=int, default=5)
    ap.add_argument("--prefix", default="1NT Pass")
    ap.add_argument("--dealer", default="S")
    ap.add_argument("--card", default="Basic-Bridge")
    ap.add_argument("--scoring", nargs="+", default=["MP"])
    ap.add_argument("--vuls", nargs="+", default=["None"])
    ap.add_argument("--partners", type=int, default=40)
    ap.add_argument("--seed", type=int, default=1)
    a = ap.parse_args()
    rng = random.Random(a.seed)

    partners = []
    while len(partners) < a.partners:
        h = deal13(rng)
        L = sorted(lengths(h))
        if 15 <= hcp(h) <= 17 and L[0] >= 2 and L[3] <= 5 and L != [2, 2, 4, 5]:
            partners.append(pbn(h))

    def partner_for(h):
        # A balanced 15-17 from the other 39 cards.
        for _ in range(100000):
            p = deal13(rng, avoid=set(h))
            L = sorted(lengths(p))
            if 15 <= hcp(p) <= 17 and L[0] >= 2 and L[3] <= 5 and L != [2, 2, 4, 5]:
                return pbn(p)
        raise SystemExit("no partner found")

    hands, seen = [], set()
    tries = 0
    while len(hands) < a.count and tries < a.count * 5000:
        tries += 1
        h = deal13(rng)
        L = lengths(h)
        if not (a.hcp[0] <= hcp(h) <= a.hcp[1]):
            continue
        if L[0] > a.max_major or L[1] > a.max_major:
            continue
        if min(L) < a.min_len or max(L) > a.max_len:
            continue
        p = pbn(h)
        if p not in seen:
            seen.add(p)
            hands.append((p, partner_for(h)))

    q = lambda xs: "[" + ", ".join(f'"{x}"' for x in xs) + "]"
    with open(a.out, "w") as f:
        f.write(f"# Generated by probes/gen_hands.py: {len(hands)} hands, HCP {a.hcp}, "
                f"majors <= {a.max_major}, lengths {a.min_len}-{a.max_len}, seed {a.seed}\n")
        f.write(f'card    = "{a.card}"\ndealer  = "{a.dealer}"\nprefix  = "{a.prefix}"\n')
        f.write(f"vuls    = {q(a.vuls)}\nscoring = {q(a.scoring)}\n")
        f.write(f"partner = {q(partners)}\n")
        f.write('our     = ["general.style=bba"]\n')
        f.write("hands = [\n" + "".join(f'  "{h} | {h} | {p}",\n' for h, p in hands) + "]\n")
    print(f"{a.out}: {len(hands)} hands, {len(partners)} partners")


if __name__ == "__main__":
    main()
