//! Scenarios in a Practice-Bidding-Scenarios checkout: `bba/<name>.pbn`
//! bid by BBA, and `btn/<name>.btn` naming the cards each side played.

use std::path::{Path, PathBuf};

/// Cards the PBS build uses when a `.btn` names none.
const DEFAULT_NS: &str = "21GF-DEFAULT";
const DEFAULT_EW: &str = "21GF-GIB";

#[derive(Debug, Clone)]
pub struct Scenario {
    pub name: String,
    pub pbn: PathBuf,
    /// Card names: files `bbsa/<name>.bbsa`.
    pub ns_card: String,
    pub ew_card: String,
    /// What produced the reference file, from its `% Generated by` header
    /// (different BBA builds bid differently).
    pub generator: String,
}

/// Does `name` match `pattern`? `*` stands for any run of characters and
/// `?` for one; everything else is literal, so a pattern without either is
/// an exact name.
pub fn matches(pattern: &str, name: &str) -> bool {
    let (p, n): (Vec<char>, Vec<char>) = (pattern.chars().collect(), name.chars().collect());
    // The usual backtracking walk: remember the last `*` and, when the rest
    // fails, let it swallow one more character.
    let (mut i, mut j) = (0, 0);
    let (mut star, mut after_star) = (None, 0);
    while j < n.len() {
        if i < p.len() && (p[i] == '?' || p[i] == n[j]) {
            i += 1;
            j += 1;
        } else if i < p.len() && p[i] == '*' {
            star = Some(i);
            i += 1;
            after_star = j;
        } else if let Some(s) = star {
            i = s + 1;
            after_star += 1;
            j = after_star;
        } else {
            return false;
        }
    }
    p[i..].iter().all(|&c| c == '*')
}

/// Every scenario under `pbs/bba`, or those matching a pattern in `only`
/// (`Basic_*`; quote it so the shell leaves it alone).
pub fn discover(pbs: &Path, only: &[String]) -> Result<Vec<Scenario>, String> {
    let dir = pbs.join("bba");
    let entries = std::fs::read_dir(&dir).map_err(|e| format!("{}: {e}", dir.display()))?;
    let mut out = Vec::new();
    for entry in entries.flatten() {
        let path = entry.path();
        if path.extension().is_none_or(|e| e != "pbn") {
            continue;
        }
        let name = path
            .file_stem()
            .unwrap_or_default()
            .to_string_lossy()
            .to_string();
        if !only.is_empty() && !only.iter().any(|p| matches(p, &name)) {
            continue;
        }
        let (ns_card, ew_card) = cards_for(&pbs.join("btn").join(format!("{name}.btn")));
        let generator = generator_of(&path);
        out.push(Scenario {
            name,
            pbn: path,
            ns_card,
            ew_card,
            generator,
        });
    }
    out.sort_by(|a, b| a.name.cmp(&b.name));
    if !only.is_empty() {
        for want in only {
            if !out.iter().any(|s| matches(want, &s.name)) {
                return Err(format!(
                    "no scenario matching {want:?} in {}",
                    dir.display()
                ));
            }
        }
    }
    Ok(out)
}

/// The `% Generated by ...` comment at the top of a reference PBN.
fn generator_of(pbn: &Path) -> String {
    use std::io::{BufRead, BufReader};
    let Ok(f) = std::fs::File::open(pbn) else {
        return "unknown".into();
    };
    BufReader::new(f)
        .lines()
        .take(10)
        .map_while(Result::ok)
        .find_map(|l| {
            l.trim()
                .strip_prefix("% Generated by ")
                .map(|g| g.trim().to_string())
        })
        .unwrap_or_else(|| "unknown".into())
}

/// The `# convention-card-ns:` / `-ew:` lines of a `.btn`.
fn cards_for(btn: &Path) -> (String, String) {
    let text = std::fs::read_to_string(btn).unwrap_or_default();
    let find = |key: &str| {
        text.lines()
            .find_map(|l| l.trim().strip_prefix(key).map(|v| v.trim().to_string()))
            .filter(|v| !v.is_empty())
    };
    (
        find("# convention-card-ns:").unwrap_or_else(|| DEFAULT_NS.into()),
        find("# convention-card-ew:").unwrap_or_else(|| DEFAULT_EW.into()),
    )
}

#[cfg(test)]
mod tests {
    use super::matches;

    #[test]
    fn patterns_match_scenario_names() {
        assert!(matches("Basic_NT", "Basic_NT"));
        assert!(!matches("Basic_NT", "Basic_NTX"));
        assert!(matches("Basic_*", "Basic_Takeout_Double"));
        assert!(matches("Basic_*", "Basic_"));
        assert!(!matches("Basic_*", "1N"));
        assert!(matches("*Overcall*", "Opps_Preemptive_Overcall"));
        assert!(matches("*", "anything"));
        assert!(matches("1N?", "1N5"));
        assert!(!matches("1N?", "1N"));
        // Backtracking: the first `*` must give characters back.
        assert!(matches(
            "*_Double",
            "Responsive_Double_after_Overcall_Double"
        ));
        assert!(!matches("*_Double", "Responsive_Double_after_Overcall"));
    }
}
